#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/index.js"
compatibility_date = "2024-08-22"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_FULL_KV", id = "8943789ed0af49659f887fc740d11240" }
]
