#:schema node_modules/wrangler/config-schema.json
name = "sub-full"
main = "src/index.js"
compatibility_date = "2025-08-22"
compatibility_flags = ["nodejs_compat"]

# D1 数据库配置
[[d1_databases]]
binding = "SUBLINK_DB"
database_name = "sublink-worker-db"
database_id = "32ad5aa0-9237-4012-947f-6bbab4ea9a41"

# 保留KV用于短链接等临时数据
kv_namespaces = [
  { binding = "SUBLINK_FULL_KV", id = "39414c72dd60475499e5783e1fe34f51" }
]