#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/index.js"
compatibility_date = "2024-08-22"
compatibility_flags = ["nodejs_compat"]

# D1 数据库配置
[[d1_databases]]
binding = "SUBLINK_DB"
database_name = "sublink-worker-db"

# 保留KV用于短链接等临时数据
kv_namespaces = [
  { binding = "SUBLINK_FULL_KV", id = "Tuple214sjkfj1241241kslfk@" }
]

# 环境变量配置
[vars]
# 管理员用户名，默认为 admin
ADMIN_USER = "admin"

# 管理员密码需要在部署时设置，或通过 wrangler secret 命令设置
# 示例：wrangler secret put ADMIN_PASSWORD
