#:schema node_modules/wrangler/config-schema.json
name = "sub-"
main = "src/index.js"
compatibility_date = "2024-08-22"
compatibility_flags = ["nodejs_compat"]

# D1 数据库配置
[[d1_databases]]
binding = "SUBLINK_DB"
database_name = "sublink-worker-db"
database_id = "0dc31a4b-9eff-4dc4-8686-6729b505e0f1"

# 保留KV用于短链接等临时数据
kv_namespaces = [
  { binding = "SUBLINK_FULL_KV", id = "292880ed0af392400fc740d22806" }
]