#:schema node_modules/wrangler/config-schema.json
name = "sub-full"
main = "src/index.js"
compatibility_date = "2025-08-22"
compatibility_flags = ["nodejs_compat"]

# KV存储绑定
kv_namespaces = [
  { binding = "SUBLINK_FULL_KV", id = "31f210a25b9b4e96b27b303b1edd5d94" },
  { binding = "TEMP_TOKENS", id = "新生成的ID" }
]

# D1数据库绑定
[[d1_databases]]
binding = "SUB_STORE_DB"
database_name = "sub-store-db"
database_id = "32ad5aa0-9237-4012-947f-6bbab4ea9a41"